version: 0.0
os: linux
files:
  - source: /
    destination: /srv/sektor/backend/
hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: ubuntu